x-config:
  dockerfile: &dockerfile tutorials/stdpar/brev/dockerfile
  image: &image ghcr.io/nvidia/stdpar-tutorial:latest
  working-dir: &working-dir /accelerated-computing-hub/tutorials/stdpar/notebooks

services:
  base:
    build:
      context: ../../..
      dockerfile: *dockerfile
    image: *image
    pull_policy: missing
    volumes:
      - accelerated-computing-hub:/accelerated-computing-hub
    environment:
      - BREV_ENV_ID
      - ACH_DISABLE_GIT_PULL_ON_START
    user: root
    working_dir: *working-dir
    entrypoint: ["/accelerated-computing-hub/brev/base-start.bash"]
    restart: "no"
  jupyter:
    image: *image
    depends_on:
      base:
        condition: service_completed_successfully
    privileged: true
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8888:8888" # JupyterLab
    volumes_from:
      - base
    environment:
      - BREV_ENV_ID
      - ACH_DISABLE_GIT_PULL_ON_START
    user: root
    working_dir: *working-dir
    restart: unless-stopped
  nsight:
    image: nvcr.io/nvidia/devtools/nsight-streamer-nsys:2025.3.1
    depends_on:
      base:
        condition: service_completed_successfully
    pull_policy: missing
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "0.0.0.0:8080:8080" # HTTP
      - "0.0.0.0:3478:3478" # TURN
    volumes_from:
      - base
    environment:
      - BREV_ENV_ID
      - ACH_DISABLE_GIT_PULL_ON_START
    user: root
    working_dir: *working-dir
    entrypoint: ["/accelerated-computing-hub/brev/nsight-start.bash"]
    restart: unless-stopped

volumes:
  accelerated-computing-hub:
